### ISSUE TITLE
PHP8 AddOn kann nicht installiert werden

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/focuspoint#101]
AddOn focuspoint konnte aus folgendem Grund nicht aktualisiert werden:
Die PHP-Version (8.0.0) entspricht nicht der geforderten Versionsbedingung ^7.1!

**Comment by christophboecker** [comment]
Ich kann die Versionsanforderung auf >=7.1 ändern, aber nicht mit php 8.0 testen. Nur um es erwähnt zu haben.

**Comment by christophboecker** [comment]
So, Release 3.0.1 angefertigt aber noch nicht im Installer. Wäre nett wenn Du es mal mit php 8 testen könntest.

**Comment by skerbis** [comment]
Check , getestet

**Comment by skerbis** [comment]
Danke

**Comment by christophboecker** [comment]
Ist im Installer sichtbar; Issue geschlossen mit #102; Danke für den Hinweis und den Test
