### ISSUE TITLE
Exception: Unable to fetch row. // Beim Anlegen eines MediaManger Typen

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/focuspoint#103]
**Request-Uri:** /redaxo/index.php?page=media_manager/types&func=add&list=339ec9aa&type_id=0
**Request-Method:** POST

**rex_sql_exception:** Unable to fetch row.
**File:** redaxo/src/core/lib/sql/sql.php
**Line:** 812

<details>
<summary>Stacktrace</summary>

| Function | File | Line |
| -------------------------------------------- | ------------------------------------------------------- | -------- |
| rex_sql->getRow | redaxo/src/core/lib/sql/sql.php | 787 |
| rex_sql->fetchValue | redaxo/src/core/lib/sql/sql.php | 734 |
| rex_sql->getValue | redaxo/src/addons/url/lib/Url/ExtensionPointManager.php | 139 |
| Url\ExtensionPointManager->normalize | redaxo/src/addons/url/lib/Url/ExtensionPointManager.php | 47 |
| Url\ExtensionPointManager->__construct | redaxo/src/addons/url/boot.php | 39 |
| rex_package->{closure} | redaxo/src/core/lib/extension.php | 51 |
| rex_extension::{closure} | redaxo/src/core/lib/util/timer.php | 63 |
| rex_timer::measure | redaxo/src/core/lib/extension.php | 62 |
| rex_extension::registerPoint | redaxo/src/core/lib/form/form.php | 389 |
| rex_form->save | redaxo/src/core/lib/form/form_base.php | 1157 |
| rex_form_base->get | redaxo/src/addons/media_manager/pages/types.php | 193 |
| include | redaxo/src/core/lib/packages/package.php | 280 |
| rex_package->includeFile | redaxo/src/core/lib/be/controller.php | 482 |
| rex_be_controller::{closure} | redaxo/src/core/lib/util/timer.php | 63 |
| rex_timer::measure | redaxo/src/core/lib/be/controller.php | 483 |
| rex_be_controller::includePath | redaxo/src/core/lib/be/controller.php | 432 |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/media_manager/pages/index.php | 22 |
| include | redaxo/src/core/lib/packages/package.php | 280 |
| rex_package->includeFile | redaxo/src/core/lib/be/controller.php | 482 |
| rex_be_controller::{closure} | redaxo/src/core/lib/util/timer.php | 63 |
| rex_timer::measure | redaxo/src/core/lib/be/controller.php | 483 |
| rex_be_controller::includePath | redaxo/src/core/lib/be/controller.php | 415 |
| rex_be_controller::includeCurrentPage | redaxo/src/core/backend.php | 233 |
| require | redaxo/src/core/boot.php | 141 |
| require | redaxo/index.php | 9 |

</details>
<details>
<summary>System report (REDAXO 5.12.0-beta2, PHP 7.3.1, MySQL 5.7.25)</summary>

| REDAXO | |
| ------------: | :----------- |
| Version | 5.12.0-beta2 |

| PHP | |
| ------------: | :--------- |
| Version | 7.3.1 |
| OPcache | no |
| Xdebug | no |

| Database | |
| ------------: | :----------- |
| Version | MySQL 5.7.25 |
| Character set | utf8mb4 |

| Server | |
| ------------: | :--------- |
| OS | Darwin |
| SAPI | cgi-fcgi |
| Webserver | Apache |

| Request | |
| ------------: | :------------ |
| Browser | Safari/14.0.3 |
| Protocol | HTTP/1.1 |
| HTTPS | yes |

| Packages | |
| --------------------------: | :----------- |
| accessdenied | 1.0.6 |
| adminer | 1.8.3 |
| backup | 2.7.0-beta2 |
| be_password | 2.0.0 |
| be_style | 2.12.0-beta2 |
| be_style/customizer | 2.12.0-beta2 |
| be_style/redaxo | 2.12.0-beta2 |
| bloecks | 3.0.2 |
| bloecks/cutncopy | 3.0.2 |
| bloecks/status | 3.0.2 |
| cronjob | 2.8.0-beta2 |
| developer | 3.9.0 |
| focuspoint | 3.0.1 |
| getaweb | 1.0.0 |
| grid | 0.1.0-dev |
| install | 2.9.0-beta2 |
| mblock | 3.1.0 |
| media_manager | 2.11.0-beta2 |
| media_srcset | 2.0.2 |
| mediapool | 2.10.0-beta2 |
| mediapool_rename | 1.0.0 |
| metainfo | 2.8.0-beta2 |
| mform | 5.3.1 |
| mform/docs | 1.0 |
| modulsammlung | 4.15.2 |
| modulsammlung/documentation | 1.0 |
| navigation_array | 1.1.1 |
| phpmailer | 2.10.0-beta2 |
| project | dev |
| project_manager | 1.3.0 |
| project_manager/client | 1.1.0 |
| quick_navigation | 4.0.0 |
| redactor | 2.1.0 |
| search_it | 6.7.3 |
| search_it/documentation | 6.7.3 |
| search_it/plaintext | 6.7.3 |
| search_it/stats | 6.7.3 |
| sprog | 1.2.0 |
| structure | 2.12.0-beta2 |
| structure/content | 2.12.0-beta2 |
| theme | 1.2.0 |
| uploader | 2.2.1 |
| url | 2.0.0-beta3 |
| users | 2.8.0-beta2 |
| yform | 3.4.1 |
| yform/email | 3.4.1 |
| yform/manager | 3.4.1 |
| yform/tools | 3.4.1 |
| yform_spam_protection | 1.0.5 |
| yform_usability | 1.4 |
| yrewrite | 2.7 |

</details>

**Comment by christophboecker** [comment]
Ich seh jetzt grade nicht den Link zu Focuspoint. Bei mir klappt esjedenfalls problemlos, einen Typen anzulegen und einen Effekt zuzuweisen.

**Comment by olien** [comment]
Danke. dann suche ich mal weiter...
