### ISSUE TITLE
PHP 8.1.5 / Redaxo 5.13.1 / Focuspoint 4.0.0 => NOK

### ISSUE THREAD

**Issue by LEAakaLAP** [FriendsOfREDAXO/focuspoint#110]
FocusPoint - Preview im Mediamanager funktioniert nicht, ebenso die korrekte Ausgabe!

PHP              8.1.5 (lt. Plesk)
Redaxo         5.13.1
FocusPoint   4.0.0

![Bildschirmfoto 2022-04-27 um 12 30 55](https://user-images.githubusercontent.com/104498524/165499513-3c7886a2-1f8d-4074-a56f-160ef480c6e3.png)

Diese Meldung erhält man, wenn man versucht den defekten Link aus DevTools zu öffnen! Hoffe es hilft

**Comment by christophboecker** [comment]
NOK ? Weiß grade nicht, was das bedeutet, sorry. Und bist Du sicher, dass der Fehler in focuspoint liegt? Ich hätte eher auf MediaManager getippt

**Comment by LEAakaLAP** [comment]
NOK = NOT OK! 
ich bin Anwender und versuche hilfreiche PlugIns zu nutzen. Ob der Fehler vom FocusPoint oder von woanders kommt, kann ich dir nicht sagen. Ich kann das AddOn auf jeden Fall nicht nutzen unter PHP 8.1.5, denn unter PHP 7.4 funktioniert es ja.

**Comment by christophboecker** [comment]
Ich hab mal auf meinem zweiten System getestet. Da war ein PHP 8.1.4 darauf, mit dem alles lief wie es sollte. Das System habe ich dann (brew) auf 8.1.5 aktualisiert. Danach gab es einen RRRRR-Whoops, den ich aber letztlich durch Deakivieren des Minibar-Addon beheben konnte. 

Was soll ich sagen, der Medienpool läuft wie er soll. In der Medienübersicht werden die Medien-Thumbnails angezeigt und in der Detailansicht gibt es die Vorschau mit der Fokuspunkt-Auswahl. 

Redaxo 5.13.2, Focuspoint 4.0.0, PHP 8.1.5.

Hast Du wirklich Redaxo 5.13.1 installiert oder ist das ein Schreibfehler. In 5.13.2 gibt es diverse Bugfixes.

**Comment by ixtension** [comment]
Kann den Bug für PHP 7.4.29 / Redaxo 5.13.3 / Focuspoint 4.0.0 bestätigen-.
![grafik](https://user-images.githubusercontent.com/17177286/171831650-ed5fdd65-bda7-46a7-8f8d-82b3e18e044d.png)
![grafik](https://user-images.githubusercontent.com/17177286/171831843-bd055920-3915-4840-a578-1559574449cb.png)

**Comment by ixtension** [comment]
die folgende Zeile in der focuspoint_api.php in line 82 fixt das Problem:
`        
       $manager->setCachePath('media_manager');
`
(`$cachePath` der Klasse `rex_media_manager `wird von der abgleiteten Klasse bei null belassen...was den Fehler wirft.)

**Comment by christophboecker** [comment]
Erledigt mit #111 und neuem Bugfix-Release 4.0.1.
