### ISSUE TITLE
Ordner `.github` im Release

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/focuspoint#114]
Ordner `.github` landet mit im Release.

**Comment by christophboecker** [comment]
Mir erschließt sich nicht, was hier bei FP anders iat als in anderen Repos wiez.B. demo_onepage. Auch da gibt es sieses Verzeichnis, aber es ist nicht im Realease-Zip. 

Help wellcome. @schuer Hättest Du einen Tip, Dirk?

**Comment by schuer** [comment]
@christophboecker Du veröffentlichst doch mittels der Installer Action. Die ignoriert eigentlich den `.github`-Ordner. Sieht man auch schön in den Logs, beispielhaft bei einem anderen AddOn:

<img width="911" alt="grafik" src="https://user-images.githubusercontent.com/1297466/207621384-82049827-5cb9-4403-ad40-51b3656e390a.png">

(Die Logs vom letzten FP-Release sind schon zu alt, deshalb kann man die nicht mehr anschauen.)

Will sagen: Wenn wirklich der `.github`-Ordner mit im Release ist, wäre das eigenartig.

**Comment by christophboecker** [comment]
Das letzte Release ist vom 18. Juni. Und der Ordner ist drin. Hm.

**Comment by schuer** [comment]
Mit Ruhe nochmal draufgeschaut: Der `.github`-Ordner scheint in anderen Releases ebenso enthalten zu sein. Sicherlich kein Problem dieses Repos, sondern der [Installer-Action](https://github.com/FriendsOfREDAXO/installer-action).

Ich schließe mal. Bei Bedarf gerne wieder öffnen.
