### ISSUE TITLE
whoops unter PHP 8.2: Implicit conversion from float (number) to int loses precision

### ISSUE THREAD

**Issue by tyrant88** [FriendsOfREDAXO/focuspoint#115]
**Description / Beschreibung**
![Zwischenablage-1](https://user-images.githubusercontent.com/1277494/210266204-d0c467c7-9c5f-4997-ab82-fcbaf6abeaeb.jpg)

REDAXO: 5.14.2
PHP: 8.2.0
Database: MySQL 5.7.31
Browser: 
AddOns: 
focuspoint | 4.0.2

**ErrorException:** Implicit conversion from float 1137.7777777777778 to int loses precision
**File:** src\addons\focuspoint\lib\effect_focuspoint_fit.php
**Line:** 220

**Comment by christophboecker** [comment]
Hatte ich ähnlich vor ein paar Wochen auf Slack, da war es PHP 8.1 und nur eine deprecated-Warnung. Da ich den Fehler nicht nachstellen konnte, war auch keine Abhilfe meinerseits möglich. 

Könnest Du mir bitte das Bild und die genaue Konfiguration des Effektes bzw. des ganzen media-typs (falls mehr als der FFFit-Effekt) zugänglich machen. Danke.

**Comment by tyrant88** [comment]
Ja nu. Ist halt, wenn einer der Werte nicht ganzzahlig ist. Die Werte sind auf dem screenshot drauf. Ich denke das ist eher ein allgemeines Ding, als ein Problem mit einem speziellen Bild.

**Comment by christophboecker** [comment]
Na gut, dann muss ich es halt so versuchen: 

- Quellbild 1920x640 (hab ich mir zurechtgeschnitzt), FP ist `50%/50%`
- Zielgröße 1137x640  => Fit-Effekt soll ein Zielbild dieser Größe erzeugen
  <img width="1030" alt="grafik" src="https://user-images.githubusercontent.com/10065904/210321408-2fcf070d-7663-4751-b8b2-975be8cf9b69.png">
- Cache gelöscht
- Im Effekt einen Dump/Exit hinter das fehlerauslösende Statement gesetzt.
  <img width="475" alt="grafik" src="https://user-images.githubusercontent.com/10065904/210319705-0f0be951-7fc2-4365-821c-644d6e64ebcc.png">
- Wenn Zeile 220-222 den Whoops auslöst, wird der Dump ja gar nicht erreicht. Umgekehrt: kommt der Dump gab es auch keinen Fehler.
- Bild per direktem Link `index.php?rex_media_type=test1137x640&rex_media_file=hiker1920x640.jpg` aufgerufen

Tja, ich komme im Test zu diesem Dump:
```
 array:16 [▼
    "gdimage" => GdImage {#64 ▼
        +size: "1920x640"
        +trueColor: true
    }
    "sw" => 1920
    "sh" => 640
    "sr" => 3
    "fx" => 960
    "fy" => 320
    "dw" => 1137
    "dh" => 640
    "zoom" => 0
    "dr" => 1.7765625
    "too_wide" => true
    "cw" => 1137
    "ch" => 640
    "cx" => 392.0
    "cy" => 0
    "des" => GdImage {#66 ▼
        +size: "1137x640"
        +trueColor: true
    }
]
```
Deshalb noch mal die Bitte, mir weitere Informationen, insbesondere wie bei Dir der Effekt konfiguriert ist, zur Verfügung zu stellen. Vieleicht kann ich den Fehler ja dann reproduzieren.

----
Testauf nem Mac mit Brew (Apache, PHP 8.2.0), Redaxo/Addons auf dem neuesten Installer-Stand von heute mogen.

**Comment by tyrant88** [comment]
Also:
Es handelt sich um ein Bild aus einem feeds stream, das musste ich erstmal raussuchen...
wobei es wie gesagt eigentlich egal ist, aber damit du nach deiner Weise vorgehen kannst:
![feeds 14](https://user-images.githubusercontent.com/1277494/210381026-56f02f86-a710-454f-9b34-a9691189e570.jpg)

Der Effekt berechnet natürlich was, sonst würden ja die Kommastellen nicht entstehen:
![Zwischenablage-2](https://user-images.githubusercontent.com/1277494/210381205-01e3d0ba-67cd-4bcd-a248-50c19ed428b6.jpg)

Mit dem "cx" Parameter und dem Wert "392.0" bei dir in deinem Beispiel scheint der Code klarzukommen. Bei mir entsteht in "dw" und "cw" der Wert "1137.7777778".
