### ISSUE TITLE
Deprecated Meldung 

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/focuspoint#118]
Core und AddOns aktuell (aus dem Installer) / PHP 8.1.13

![image](https://user-images.githubusercontent.com/330516/224305901-590dc6be-1a1c-41b2-97ee-884981be1f05.png)

https://github.com/FriendsOfREDAXO/focuspoint/commit/3d4c11387e1a6f757d88f69e97209dff1f80c525

half leider nicht

**Comment by christophboecker** [comment]
@olien Bei mir kommt der Fehler nicht. Trotzdem: wenn ich (1) den Cache lösche und (2) nur die Bild-Url-Abrufe und (3) vor Zeile 221 ein `dd(get_defined_vars());` setze, kommt beim Testbild diese Ausgabe:
```
[^]array:16 [▼
    "gdimage" => GdImage {#70 ▶}
    "sw" => 1291
    "sh" => 855
    "sr" => 1.5099415204678
    "fx" => 648
    "fy" => 447
    "dw" => 500
    "dh" => 500
    "zoom" => 0
    "dr" => 1
    "too_wide" => true
    "cw" => 500
    "ch" => 500
    "cx" => 398.0
    "cy" => 197.0
    "des" => GdImage {#72 ▶}
```
Die Nachkommastelle bei cx und cy verschwindet, wenn ich Zeile 197/198 auf int caste:
```php
			$cx = (int)($fx - floor( $cw/2 ));
			$cy = (int)($fy - floor( $ch/2 ));
 ```
Könntest Du bitte die beiden Zeilen bei Dir einbauen und schauen, was sich ändert. Bzw. ob der Fehler dann weg ist.

Danke vorab.

**Comment by olien** [comment]
Hm. Die Zeilennummern passen nicht 100%ig.
Wo genau sollte ich das DD machen? Hab keine dump hinbekommen.

Wenn ich $cx & $cy ändere bleibt der Fehler trotzdem

![image](https://user-images.githubusercontent.com/330516/224539003-1294e0b7-ea73-45a7-a42e-36415acc5164.png)

Interessanterweise kommt der nur beim ersten Aufruf des Bildes...

**Comment by christophboecker** [comment]
Cache löschen! Wenn das Bild einmal (falsch) drin ist .... DD verhindert dann, das der Cache neu geschrieben wird. 

![grafik](https://user-images.githubusercontent.com/10065904/224547561-faeba039-74b9-467b-a9d9-8131d2f853e0.png)

**Comment by olien** [comment]
![image](https://user-images.githubusercontent.com/330516/225648236-20400756-6b92-4d1c-8b8e-0fc7635920e4.png)

**Comment by christophboecker** [comment]
Moin, Oliver

Ich kann die Sache so nicht nachvollziehen. Keine Ahnung, was da in Deiner Installation klemt, aber nach einer aktuellen 4.0.3 sieht das nicht aus. Ich habe FP 4.0.3 aus dem Installer installiert, einen Test-Mediatype angelegt (nur FP-fit als effekt, Zielgröße 800x600 ohne Zoom), nur den `dd` eingebaut und bekomme diese Ausgabe:
<img width="351" alt="grafik" src="https://user-images.githubusercontent.com/10065904/225835993-747674d9-227c-4f80-9f34-2e95381615ab.png">

Bitte poste mal, wie Dein Fit_Effekt konfiguriert ist.

**Comment by christophboecker** [comment]
Mit Skalierung in % konnte ich es nachstellen.  
Ich lös das mal radikal und caste die Werte für `imagecopyresampled` auf `int`. Am Wochenende.

**Comment by olien** [comment]
Danke sehr 😘

**Comment by christophboecker** [comment]
@olien Du köntest mal mit der Git-Version testen, bitte, bevor ich das Release erstelle. Danke.

**Comment by christophboecker** [comment]
Hab einfach mal ein Release daraus gemacht.

**Comment by olien** [comment]
Klappt. DANKE SEHR!!!!!
