### ISSUE TITLE
focus point vs media_negotiator

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/focuspoint#120]
wenn ich media_neotiator https://github.com/AndiLeni/media_negotiator/issues/11 verwende. Erhalte ich immer JPGs als Ergebnis. 
Eigentlich sollten dann aber Webp ausgeliefert werden oder eben das was der Browser kann. 

https://github.com/AndiLeni/media_negotiator/issues/11

**Comment by christophboecker** [comment]
Ich mach mal zu nach der ausführlichen Diskussion im Slack. Weder Andi noch ich können den Fehler nachstellen. Code-Exegese durch die Slack-beteiligten (Thomas, Gregor, Andi und ich) findet auch keinen Hinweis. 

Gerne wieder öffnen, wenn es opportun erscheint oder neue Erkenntnisse auftauchen, die auf FP deuten.
