### ISSUE TITLE
Whoops nach Update auf 4.1.0

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/focuspoint#129]
Moin Christoph...
Hab dein Focuspoint Update durchgeführt (auf 4.1.0) und seitdem whoopt es wenn ich im MediaManger einen neuen Effekt hinzufügen möchten (Klick auf das Plus-Icon in der MediaType-Ansicht)...
Das passiert sowohl in Redaxo 5.15.1 als auch in der 5.16.0beta1...
Ich hänge den Whoops mal an und hoffe du kannst damit etwas anfangen?

REDAXO: 5.15.1 und 5.16.0beta1
PHP: 8.2.13
Database: MariaDB 10.6.16

![Screenshot 2024-02-03 135918](https://github.com/FriendsOfREDAXO/focuspoint/assets/10958385/8073983f-c4e8-4430-88ef-6bcb874d02b9)

**Comment by christophboecker** [comment]
Mercie, Stefan, für die Meldung. Die Zeile mit dem array_walk ist Quatsch, Das StrToLower soll die Query übernehmen. Neue Version 4.2 mit Bugfix und Änderungen wg. Namespace folgt vermutlich morgen.

**Comment by christophboecker** [comment]
Erledigt mit #131 und #132
