### ISSUE TITLE
Include einer nicht existierenden Datei

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/focuspoint#133]
**Description / Beschreibung**

Diese Datei existiert nicht
https://github.com/FriendsOfREDAXO/focuspoint/blob/master/install.php#L39

**Affected versions / Verwendete Versionen**
Version: 4.2.0

**Did it whoops? / Whoops erhalten?**
Warning: include_once(/src/addons/focuspoint/lib/effect_focuspoint.php): Failed to open stream: No such file or directory in [src/addons/focuspoint/install.php](phpstorm://open?file=/src/addons/focuspoint/install.php&line=39) on line 39

**Comment by christophboecker** [comment]
Danke für´s Aufspüren.
