### ISSUE TITLE
Redaxo Setup : Integrity constraint violation: 1048 Column 'type_id' cannot be null

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/focuspoint#138]
**Description / Beschreibung**
Bei einem Re-Setup und beim Install des Addons erhalte ich die untenstehende Meldung.

In der install.php scheint man bereits darüber gestolpert zu sein. Siehe
https://github.com/FriendsOfREDAXO/focuspoint/blob/master/install.php#L226-L227

Die Variable `$mm_type_id` ist nicht definiert bzw. darf nicht `null` sein.

**Did it whoops? / Whoops erhalten?**

> AddOn focuspoint konnte aus folgendem Grund nicht installiert werden:
> SQL error: Error while executing statement "INSERT INTO `rex_media_manager_type_effect` SET `type_id` = :type_id, `effect` = :effect, `parameters` = :parameters, `updatedate` = :updatedate, `updateuser` = :updateuser, `createdate` = :createdate, `createuser` = :createuser" using params {"type_id":null,"effect":"resize","parameters":"{\"rex_effect_resize\":{\"rex_effect_resize_width\":\"1024\",\"rex_effect_resize_height\":\"1024\",\"rex_effect_resize_style\":\"maximum\",\"rex_effect_resize_allow_enlarge\":\"enlarge\"}}","updatedate":"2024-05-24 11:16:23","updateuser":"backend","createdate":"2024-05-24 11:16:23","createuser":"backend"}! SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'type_id' cannot be null

Nachtrag:
Die Variable `$mm_action_type` wird mit `null` gesetzt, weil es keinen Effekt gibt der den Typen `focuspoint_media_detail` enthält. Deshalb kommt das Skript weiter unten nicht in das `if`, wo dann  `$mm_type_id` gesetzt wird.
https://github.com/FriendsOfREDAXO/focuspoint/blob/master/install.php#L152

--

| Upgrade | vorher | nachher |
| ---| ---| ---|
| REDAXO | 5.8.1 | 5.17 |
| Focuspoint | 3.0.2 | 4.2.2 |

**Comment by christophboecker** [comment]
Hm. Schwierig. Ich habe den Fehler nicht nachstellen können. Zuletzt habe ich mir ein frisches 5.8.1 angelegt und darin FP 3.0.2 installiert. Update von 5.8.1. direkt auf 5.17.1. crashte, so dass ich das Update in mehreren Schritten gemacht hab. Dann erst FP direkt auf 4.2.2 gezogen. Fehlerfrei. Ich schau mal weiter ....

**Comment by tbaddade** [comment]
Es muss vermutlich eine Version geben, wo der Effekt für den Detail MediaType nicht dabeizustehen. Genau dann kommt der Fehler.

Mit der Redaxo Version hat das m.E. nichts zu tun. Wenn der obige Effekt nicht angelegt ist, müsste der Fehler kommen.

**Comment by christophboecker** [comment]
Möglicherweise hilft das hier:

[Zeile 152](https://github.com/FriendsOfREDAXO/focuspoint/blob/master/install.php#L152), also 
```php
$mm_action_type = null === ($mm_type[0]['id'] ?? null);
```
so ändern, dass hier bereits `$mm_type_id` gesetzt wird, also
```php
$mm_type_id = $mm_type[0]['id'] ?? null;
$mm_action_type = null === $mm_type_id;
```
Könntest Du das mit Deinen Daten testen, Thomas?

**Comment by tbaddade** [comment]
Müsste so funktionieren. 

Das Testen mit den Daten geht leider nicht mehr, da ich das Update bereits am Freitag einspielen musste.
