### ISSUE TITLE
css ids der input fields im Medienpool Formular heißen nicht so wie im Code der Klasse

### ISSUE THREAD

**Issue by tyrant88** [FriendsOfREDAXO/focuspoint#14]
Die Felder im Medienpool sehen so aus:
<input class="form-control" id="rex-metainfo-med_focuspoint_data" name="med_focuspoint_data" value="0.04,-0.41" type="text">

in der Klasse `class.rex_focuspoint.inc.php` steht 
```  $('#Focuspoint_Data' ).val(focusX.toFixed(2) + ',' + focusY.toFixed(2));
     $('#Focuspoint_CSS' ).val(backgroundPositionCSS); ```

Das kann nicht klappen, oder?

**Comment by olien** [comment]
Ist in Version 1.3.3 korrigiert.
Danke!
