### ISSUE TITLE
jpeg Bilder werden nicht unterstützt

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/focuspoint#20]
Liegt an dieser Zeile.
https://github.com/FriendsOfREDAXO/focuspoint/blob/master/lib/class.rex_focuspoint.inc.php#L108

**Comment by skerbis** [comment]
Diese Zeile müsste dann wohl aber auch angepasst werden: 
https://github.com/FriendsOfREDAXO/focuspoint/blob/master/lib/class.rex_focuspoint.inc.php#L106

**Comment by tbaddade** [comment]
Man kann auch über `rex_media` und die Methode `isImage()` gehen.

**Comment by olien** [comment]
Ist erledigt

**Comment by olien** [comment]
https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/mediapool/package.yml#L22

Alternative ungetestet:

$media = rex_media::get($vars[0]['filename']);
if ($media->isImage()) {
    ...
}

( Danke an @tbaddade )

**Comment by olien** [comment]
Ist wohl auch erledigt :-)
