### ISSUE TITLE
Focuspointwerte via Button löschen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/focuspoint#21]
Button unterhalb des Bildes anbringen?

**Comment by olien** [comment]
Wird gemacht

**Comment by olien** [comment]
hallo info, wärst du so lieb und aktualisierst auch das changelog?
dann kann das hier geschlossen werden - oder?

lg
oliver

**Comment by olien** [comment]
Ich schliesse mal hier. Danke!
