### ISSUE TITLE
Überflüssige Felder beim hinzufügen eines Mediums

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/focuspoint#25]
Focuspoint Data
Focuspoint CSS

**Comment by olien** [comment]
Die Felder sind im Medienpool bei "Medium hinzufügen" und "Dateien synchronisieren" auf

**Comment by eaCe** [comment]
Ich habe mal geschaut ob man das via EP lösen könnte. Über PAGE_MEDIAPOOL_HEADER bekommt man allerdings nur die „Startseite“ des Medienpools. Ich bin nicht sicher ob das so richtig ist… 

Man könnte dies recht dreckig lösen in dem man über die URL geht und nach den input id's sucht und diese dann via JS versteckt.. :/

**Comment by olien** [comment]
Hm.... Gefällt dir die Lösung? Oder lassen wir die Felder einfach?

**Comment by eaCe** [comment]
Gefällt mir nicht, habs aber mal mit rein genommen und ist beim PR dann dabei.

**Comment by olien** [comment]
Ok. Ich würde sagen dann kann das hier zu....
(soll wieder einer aufmachen wenn doch zu doof :-))

Danke!

**Comment by tbaddade** [comment]
> Gefällt mir nicht, habs aber mal mit rein genommen und ist beim PR dann dabei.

@eaCe Dann mache bitte 2 PRs. Einen für dieses Issue und einen für deine Weiteren Änderungen.
