### ISSUE TITLE
Menülink unter AddOns nicht anzeigen. Hilfe via ? auf der AddOnseite

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/focuspoint#27]
Die Inhalte der Tabs "Info" und "Hilfe" könnten in die Readme gehen. Changelog und Lizenz könnten in der Readme verlinkt werden. Gutes Beispiel wäre hier [Quicknavigation](https://github.com/FriendsOfREDAXO/quick_navigation)

**Comment by olien** [comment]
erledigt
