### ISSUE TITLE
Effekte im MediaManager umbenennen

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/focuspoint#29]
Hab leider die Stelle nicht gefunden wo die Übersetzungen angegeben werden können...
(Ein Eintrag in die lang-Dateien hat nichts geändert...) 

Grüße
Oliver

![unbenannt-1](https://user-images.githubusercontent.com/330516/33199591-37648452-d0f1-11e7-9b77-23881a401eab.png)

**Comment by eaCe** [comment]
In die jeweilige Effekt Klasse folgende Funktion hinzufügen:

```php
public function getName()
{
    return rex_i18n::msg('effektname_übersetzung');
}
```

**Comment by olien** [comment]
Danke. Ist erledigt!
