### ISSUE TITLE
Deprecated: Non-static method rex_media_manager::effectsFromType() 

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/focuspoint#35]
Genaueres hier
https://github.com/FriendsOfREDAXO/focuspoint/pull/32#discussion_r161157975

**Comment by eaCe** [comment]
Fix:
https://github.com/FriendsOfREDAXO/focuspoint/commit/deb8b313e87b639740d03bb0ab05f48b70b839f1
