### ISSUE TITLE
Neues Relase erstellen und in den Installer laden

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/focuspoint#38]

**Comment by tbaddade** [comment]
@olien Könntest du das demnächst machen?

**Comment by olien** [comment]
Release habe ich erstellt. In den Installer hochladen kann ich es gerade nicht.

> Der Webservice liefert folgende Fehlermeldung: API-Login ist fehlgeschlagen!

**Comment by tbaddade** [comment]
> Release habe ich erstellt.

Danke dir.

> In den Installer hochladen kann ich es gerade nicht.

Woran hakt es?

**Comment by olien** [comment]
> API-Login ist fehlgeschlagen!

Entweder habe ich den falschen FOR Key (wurde der geändert?) oder es liegt daran, dass ich ne lokale Installtion via MAMP nutze

**Comment by skerbis** [comment]
Es liegt an MAMP
Mit Docker geht's

**Comment by olien** [comment]
Könntest du das eben in den installer schieben?

**Comment by skerbis** [comment]
japp

**Comment by olien** [comment]
Es gibt schon wieder ne neue Version :-))
