### ISSUE TITLE
Vorschau: Mediatypen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/focuspoint#40]
- Nur Mediatypen zeigen, die focuspoint verwenden. 
- Keine rex_mediabutton_preview, rex_mediapool_detail usw. auflisten

**Comment by olien** [comment]
Find ich gut. habe gerade eine ellenlange Liste an Mediatypen....

**Comment by eaCe** [comment]
Wenn es um die Vorschau geht die ich eingebaut hatte, kann ich mich dem annehmen.

**Comment by skerbis** [comment]
Gerne. Übringens, @eaCe tolles Feature
