### ISSUE TITLE
Datenbank bereinigen; nur noch 1 Feld

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/focuspoint#45]
Hallo zusammen,

es gibt ein paar Ideen, das Focuspoint-Addon etwas zu überarbeiten. Ein Thema ist die Datenhaltung.
Ich würde das gerne etwas umgestalten. Insbesondere stört mich, dass zwei Felder geführt werden, deren Inhalte aber synchron sein müssen. Dass es zwei Felder sind, hat historische Gründe; muss man aber nicht in alle Ewigkeit fortführen.

Konkret wird die Koordinate in zwei Formaten gespeichert und in zwei Feldern: 

- med_focuspoint_css
- med_focuspoint_data

Das css-Feld ist quasi html/css-kompatibel. Nullpunkt ist oben links, Maßangaben sind x% von Bildbreite bzw. Bildhöhe, also Werte von 0 bis 100.

Das data-Feld verortet den Nullpunkt in der Mitte des Bildes. Die Werte gehen jeweils von -1.00 bis 1.00. Die Genauigkeit ist also doppelt so hoch wie beim css-Feld. 

Der Effekt `focuspunkt_resize` rechnet mit dem data-Feld, `focuspunkt_fit` rechnet mit dem css-Feld.

Solange die Daten eh nur von den Fokuspoint-Effekten benutzt und von der Eingabe in der Sidebar der 
Medienpool-Detailseite gesetzt werden, könnte die Datenhaltung störugsfrei geändert werden; stört ja niemanden, solange das Ergebnis stimmt.

**Aber was ist mit Anwendungen gleich welcher Art, die die beiden Datenbank-Felder irgendwie nutzen oder befüllen? Habt Ihr da was laufen, das bei einer Umstellung sperrig wäre oder wo Ihr sagt: "no way - Finger weg"? YForm-Datentype, eigene MediaManager-Effekte, ...? **

Konkret wäre der Plan:

- neues Feld `med_focuspoint` einführen, die alten Felder löschen
- Feldinhalt wären %-Werte analog zum css-Feld, aber mit einer Nachkommastelle (Genauigkeit 5fach ggü. data-Feld und 10-fach ggü. css-Feld) und ohne %-Zeichen (z.B. "23.1,77.5")
- Daten aus `med_focuspoint_data` nach `med_focuspoint` transferieren
- Die Umstellung würde `update.php` vornehmen. 

Das hätte mehrere Vorteile:

- Es kann keine Abweichungen mehr geben zwischen css-Feld und data-Feld falls jemand die Felder manuell voneinander abweichend befüllt. (imho: möglichst nie zwei Felder für dieselbe Infromation) 
- Das Addon Focuspoint wird etwas vereinfacht.
- Die Datenbank wird entschlackt.
- In der Media-Detail-Seite entfällt eine Eingabezeile.

Bitte um Feedback.

Grüße
Chris

**Comment by olien** [comment]
Finde ich sehr gut!

**Comment by madiko** [comment]
Hallo Chris,
grundsätzlich finde ich es eine gute Idee, die ich unterstütze. 

Ich überblicke jedoch gerade nicht, welche Auswirkungen sich auf das AddOn LightGallery daraus ergeben. Ich habe nur grob in Erinnerung, da über genau dieses css gestolpert zu sein (kann auch im Modul gewesen sein, dass dort von Haus aus mitgeliefert wird) als ich es neulich einbaute. 

Würdest Du bitte da mal nach schauen?
https://github.com/FriendsOfREDAXO/lightgallery

Besten Dank und gutes Gelingen,
Franziska

**Comment by olien** [comment]
Da gibt es keine Abhängigkeiten...

**Comment by olien** [comment]
Theoretisch brauchen die Werte gar nicht sichtbar sein (zumindest nicht in einem fetten Input Feld..) - oder? Wie wäre es so?

![fp](https://user-images.githubusercontent.com/330516/41227541-8427ce0e-6d75-11e8-9342-392ff656d918.jpg)

**Comment by christophboecker** [comment]
Vieleicht wird es auch so:
<img width="410" alt="grafik" src="https://user-images.githubusercontent.com/10065904/41227638-d21c2984-6d75-11e8-8f72-2a3f22a5ff68.png">
Was man nicht sieht ist der Cursor, der auch als großes Fedenkreuz deherkommt und dessen Position angezeigt wird solange die Maus läuft.

**Comment by tbaddade** [comment]
> Theoretisch brauchen die Werte gar nicht sichtbar sein

Dann sollte das Bild größer dargestellt werden. Ab und zu habe ich die Werte manuell anpassen müssen.

**Comment by christophboecker** [comment]
Heute haben wir im Data-Feld 200 Werte (-1.00 bis 1.00). Mit unseren üblichen Bidschirmen sollte das Bild doch eigentlich immer größer sein als 200 px, oder. Also kann man m.E. den Punkt auch treffen. Und wenn die Cursorposition bei der Auswahl ngeeigt wird, hilft das ja auch.

Aber davon mal abgesehen ... ich halte es auch für gut, mal was manuell eingeben zu können, und würde es nicht rauswerfen wollen.

**Comment by tbaddade** [comment]
> Mit unseren üblichen Bidschirmen sollte das Bild doch eigentlich immer größer sein als 200 px, oder.

Initial wird das Bild im Medienpool mit 350px angezeigt. Da ist bei manchen Bilder zu klein.

**Comment by christophboecker** [comment]
Das bringt mich auf eine Idee: Zoom-Button. Der vertauscht einfach die Spalten-Klassen sm-8 und sm-4.

![grafik](https://user-images.githubusercontent.com/10065904/41229232-7fb8fb30-6d7b-11e8-9601-ee8b1762aff6.png)

**Comment by tbaddade** [comment]
> Das bringt mich auf eine Idee: Zoom-Button. Der vertauscht einfach die Spalten-Klassen sm-8 und sm-4.

Oder aus der **4** eine **12** machen

**Comment by IngoWinter** [comment]
Ich würde es so lassen, wie es ist. Wenn jemand das Eingabefeld für die Focuspoint Koordinaten nicht haben möchte, kann er es einfach selbst ausblenden:
```
$(document).on('ready rex:ready pjax:success', function () {
    $('[name="med_focuspoint_css"]').closest('dl').hide();
    $('[name="med_focuspoint_data"]').closest('dl').hide();
});
```
ebenso lässt sich die Vorschaugeschichte einfach ausblenden:
```
#focuspoint-reset + .btn-group {
    display: none;
}
```

**Comment by olien** [comment]
Auch eine gute Idee.. sollten wir in die Readme packen.

**Comment by marcohanke** [comment]
Wenn nur ein Feld gebraucht wird, wirde ich konsequenterweise auch die alten Zöpfe abschneiden und nur ein Feld nutzen. Mich hat es sowieso immer verwirrt dass zwei Felder da sind...

**Comment by christophboecker** [comment]
Danke für die Rückmeldungen. Ab der nächsten Version gibt es:

- Daten nur noch einmal speichern (med_focuspoint)
- Koordinate ist % der Breite bzw. Höhe mit 1 Nachkommastelle, Nullpunkt oben links.
- Erweiterung um weitere eigene Fokuspunkt-Felder
- Eigener Meta-Datentyp für die Felder

**Comment by ynamite** [comment]
Die Zoom-Funktion fände ich jetzt nicht verkehrt. Kunden die mit Focuspoint gearbeitet haben, haben mich auch schon nach einem Zoom gefragt (bin nur nicht auf die super einfache Lösung von @christophboecker gekommen, schlau!)

**Comment by christophboecker** [comment]
@ynamite Ich werkel grade an einem größeren Umbau. Zoom ist im Paket.

**Comment by madiko** [comment]
<<< hat gerade den 42. Stern drangepinnt und freut sich.

Prima Arbeit! Wirklich toll.
Gruß an alle, 
Franziska

**Comment by christophboecker** [comment]
Da der PR für V2 nun gemerged ist, kann das Issue geschlossen werden. Danke für die unterstützende Diskussion.
