### ISSUE TITLE
Wann ist eigentlich das JS verschwunden?

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/focuspoint#47]
Habe ich irgendwie übersehen...

das ```jquery_focuspoint.js``` brauche ich doch für die korrekte Platzierung von Hintergrundbildern - oder nicht?

**Comment by christophboecker** [comment]
Hmmm, gute Frage. Ich hab in irgendeiner Testinstanz  mit Fokuspunkt V 1.4.2 diese JS gefunden. Ist die wichtig? Wenn sich noch niemand beschwert hat nach dem Update ab 1.4.3, wird es wohl auch niemand vermissen :-)

Ich mache das so:

- Das Bild erzeugt der MM mit dem Effekt "fit" in definierter Größe (z.B. als 1200x300 für einen Header). Nur hier ist der Fokuspunkt relevant.
- Im Modul oder Template wird generiert `<header ... style="background-image: url(./index.php?rex_media_type=header1200&rex_media_file=whatever.jpg);">`
- Das CSS erledigt den Rest: `header { background-size: cover;  background-position: center center; }`

Von daher (und weil niemand es bisher als vermisst gemeldet hat (außer grade eben DS im Slack) würde ich das JS eh als obsolet ansehen.

**Comment by olien** [comment]
Ich habe es auch nicht wirklich gebraucht. nur vom original so übernommen. Dort gibt es ja keinen MM :-)

**Comment by skerbis** [comment]
Ich nutze nur die reine css Variante.

**Comment by christophboecker** [comment]
Irgendwie war ich de meinung, Du gehst über den Media-Manager. HAst Du mal ein Beispiel für Deine CSS-Variante, bitte, Danke.

**Comment by skerbis** [comment]
Wollte damit nur sagen, ich brauche das js nicht. In einigen Präsenzen verwende ich nur einen normalen resizer und die Positionierung des Hintergrundbildes per css. Dafür sind die Positionsdaten in den Metas ja auch da. 😏

**Comment by skerbis** [comment]
Das js macht das ggf. smoother

**Comment by christophboecker** [comment]
Ah, ok. Danke.

**Comment by olien** [comment]
Kann zu ...
