### ISSUE TITLE
SVGs und Focuspoint

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/focuspoint#48]
Wäre es möglich Focuspoint auch für SVG Dateien zu zulassen? Ginge das überhaupt?
Hab aktuell gerade das Thema, dass ein Kunde das gerne auch für SVGs einsetzen möchte (geht um Grundrisspläne).

**Comment by christophboecker** [comment]
Hab mal nachgeforscht. Es scheitert schon daran, dass der Media-Manager SVG-Dateien nicht unterstützt. Du kannst zumindest manuell Fokuspunkte in die Felder eintragen; der interaktive Teil der Eingabe läuft ebenfalls nicht, da nur die MM-bezogene URL in der Seitenleiste (die für "echte" Bilder) gesucht und ersetzt wird und nicht die einfache "Datei-Url".  

Um es abzukürzen: Du kannst z.B. das Feld Fokuspunkt CSS nutzen und musst den Wert in geeignetes HTML einfügen. Ich vermute mal, dass so etwas klappen müsste:

```
<div ... style="background-image:url(./media/dateiname.svg);background-size:cover;background-position:50% 70%;">
```
wobei "50% 70%" halt der Wert aus dem Metafeld ist. Klar: Größe des DIV muss auch irgendwie vorgegeben werden. Das korrekte Metafeld-Format wäre "50%,70%". Korrekterweise müsstest Du auch das Feld Focuspunkt-Data mit füllen, das dieselbe Koordinate in einem anderen Format aufweist. 

Stand heute wird SVG erst dann ein Thema für Fokuspoint, wenn der MM SVG unterstützt. Und schauen wir mal ...

Ach ja: bevor Du anfängst nur med_focuspoint_css zu befüllen: beim nächsten Update werden die beiden Felder zu einem. Bestandsdaten werden nur aus  med_focuspoint_data übernommen, da doppelte Genauigkeit ggü ..._css.

**Comment by christophboecker** [comment]
@ynamite Kann ich das issue schließen?

**Comment by ynamite** [comment]
Yep
