### ISSUE TITLE
Blank Screen beim Speichern

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/focuspoint#49]
Safari 11.1.2 … wenn ich auf "aktualisieren" klicke bei aktivierter Vorschau, erhalte ich einen Blankscreen.

**Comment by olien** [comment]
Version 2 ist unterwegs...

**Comment by christophboecker** [comment]
Hab den PR für die neue Version eben eingestellt. Ich hatte keinen Blankscreen beim Speichern mit Safari.
