### ISSUE TITLE
Werte werden aus dem Input nicht für die Auswahl übernommen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/focuspoint#56]
Will man die Werte im Input nachträglich anpassen, geht der Focalpoint, obwohl in der Eingabe etwas anderes steht, auf 50/50 zurück.

**Comment by christophboecker** [comment]
Danke für den Hinweis. Ich kann den Fehler nachstellen. Dann schau mer mal woran es liegt.

**Comment by christophboecker** [comment]
Und denselben Effekt habe ich auch mit allen anderen Meta-Feldern, die nichts mit FP zu tun haben. Nicht eines zeigte die Werte aus dem Record an. Konkret bei FP gesehen: an den custom_field_handler, der je vom EP aus aufgerufen wird, kam schon kein itemValue an, obwohl es das richtige Feld und der richtige Record sind. Eingegebene Werte werden aber in den Satz geschrieben. Der Weg klappt. Identisches Verhalten bei allen Meta-Feldern.

Um Abhängigkeiten zum FP-Addon zu prüfen, habe ich das Addon deinstalliert und wieder installiert. Fehler ist weg und nicht mehr reproduzierbar. Deaktivieren reichte nicht. 

Jemand eine Idee was das sein könnte? Neuinstallieren ist jedenfalls keine vertretbare Kur.

**Comment by christophboecker** [comment]
Überraschung! Das Problem ist stabil wieder da und auch durch Löschen des Cache nicht zu verscheuchen.

Focuspoint baut ja zwei Elemente in das media-Formular ein: In die Sidebar die interaktive Auswahl und in das Formular ein Custom-Feld. In beide Code-Abschnitte habe ich Kontrollausgaben eingebaut:

* An den Anfang der interaktiven Auswahl habe ich einen Dump des Media-Objektes gesetzt, einmal als `rex_media` und einmal als `focuspoint_media`. Beide Dumps zeigen, dass Felder korrekt belegt sind. `copyright`z.B. ist ein Standard-Metafeld vom Typ `text`, andere sind `custom`. Die Daten sind also da! Konkret die Felder med_copyright, med_kv30_boote und med_focuspoint.
![grafik](https://user-images.githubusercontent.com/10065904/45919085-c1c0b480-be90-11e8-9100-561b8edd8907.png)
![grafik](https://user-images.githubusercontent.com/10065904/45919125-44e20a80-be91-11e8-9be4-f6cf52619c61.png)

* Für das Custom-Feld 'Focuspoint (AddOn)' lasse ich `$ep->getSubject()` ausgeben. Da die interaktive Auswahl ihren Wert aus dem Custom-Feld ausliest, ist hier der Ansatz für die Suche. Und zu meiner Überraschung: das Feld ist leer. Nicht wegen eines Fehler im FP-Code, sondern weil über den EP METAINFO_CUSTOM_FIELD gar keine Werte übergeben werden. **An keines der Metafelder!**
![grafik](https://user-images.githubusercontent.com/10065904/45919109-17955c80-be91-11e8-8a24-fc570aca2bdf.png)
![grafik](https://user-images.githubusercontent.com/10065904/45925598-127bf000-bf19-11e8-9249-257a01e240fe.png)

* zur weiteren Kontrolle habe ich in `metainfo/lib/handler/handler.php` die Klasse `rex_metainfo_handler` gepimpt und vor dem Aufruf des EP einen Dump eingebaut. Ergebnis wiederum: keine Daten vorhanden!
![grafik](https://user-images.githubusercontent.com/10065904/45919112-267c0f00-be91-11e8-9150-23cd077a6b5a.png)

* Zudem wird die Logdatei geflutet mit solchen Meldungen:
![grafik](https://user-images.githubusercontent.com/10065904/45919264-d69e4780-be92-11e8-981c-61574f4b30f5.png)

Mir fällt schwer anzunehmen, dass die Geschichte ursächlich etwas mit dem Fokuspoint-Addon zu tun hat.  Löschen des Cache hatte keine Auswirkungen. MAMP rauf- und runterfahren hat auch nicht geholfen.

**Comment by christophboecker** [comment]
In meiner Testumgebung konnte ich klären, was das seltsame Verhalten ausgelöst hat und nachhaltig abstellen. Fehlerursache war ein anderes (privates) Addon, das ebenfalls den EP MEDIA_DETAIL_SIDEBAR belegte. In der EP-Funktion wurde die SQL-Instanz, die als $ep->getParams(['media']) zugänglich ist, mit `$ep->getParams(['media'])->getArray()` abgefragt. Ganz blöder Fehler! Abfrage mit `getValue` und die Welt ist nachhaltig in Ordnung.

**Comment by christophboecker** [comment]
Hi Thomas, hat sich bei Dir noch etwas ergeben, dass auf einen konkreten Bug in Focuspoint schließen läßt? Sonst mache ich das Issue zu.

**Comment by tbaddade** [comment]
Mit der Version `2.0.2` kann ich den Fehler nicht mehr nachstellen.
