### ISSUE TITLE
Vorschau liefert das bekannte "error" Bild

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/focuspoint#57]
Einzig die Vorschau von Focuspoint kann das Bild nicht liefern.

Über andere Urls, wie

`/media/bild.jpg`
`/images/mediatype/bild.jpg`
`/images/mediatype/400/bild.jpg`

wird das Bild korrekt angezeigt.

**Comment by christophboecker** [comment]
Bei mir nicht nachstellbar. Sorry. 

Zu den URLS kann ich nix sagen. Bei mir sehen die "klassisch" aus mit ? und viel &.

**Comment by christophboecker** [comment]
Hi Thomas, haben sich bei Dir noch Erkenntnisse zu einer möglichen Ursache ergeben? Oder ist die Sache durch?

**Comment by tbaddade** [comment]
Scheint in der Zwischenzeit behoben zu sein.

**Comment by tbaddade** [comment]
Sorry, hatte eben eine andere Version vom AddOn in der Instanz. Die Version `2.0.2`liefert immer noch das Error Bild

![screenshot 2018-12-03 09 47 53](https://user-images.githubusercontent.com/338267/49362925-863c3500-f6e0-11e8-980a-562b0019c053.png)

**Comment by christophboecker** [comment]
Das ist ja nun auch schon älter, niemand sonst meldet den Fehler, ich kann ihn nicht nachstelle. Dann schließe ich das Issue mal.
