### ISSUE TITLE
Javascript Datei fehlt um Bild im Frontend zu positionieren?

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/focuspoint#58]
Vielleicht geht es mit der neuen Version anders, aber man konnte in der 1er Version via data-Attribute die Koordinaten mitgeben und das Bild wurde dann via JS korrekt positioniert.

In der Doku habe ich dazu nichts finden können. Kannst du dazu kurz etwas schreiben, wie das mit der 2er Version funktioniert?

Hier das Original http://jonom.github.io/jquery-focuspoint/demos/full-screen/index.html

**Comment by christophboecker** [comment]
Ds Teil war gaaanz früher mal mit drin. Ist irgendwann mal rausgefallen, keine Ahnung wann und warum. Siehe Issute #47. Das JS von jonom hatte nichts mit der Erfassung im Media-Formular zu tun. Man hätte also schon damals das JS von jonom mit eigenem Code - im Frontend - aktivieren müssen. Aktuell gibt es drei Methoden:
* per media-manager und den entsprechenden Effekt
* händisch z.B. als Hintergrundbild.
* indem man das Tool von jonom installiert.

Für die beiden zweiten Varianten muss der Fokuspunkt natürlich irgendwie abgerufen werden. z.B. so:
```
$fpMedia = focuspoint_media::get( $filename );  // statt rex_media::get( $filename )
list( $x, $y) = fpMedia->getFocus();            // Abruf von "med_focuspoint" als [$x,$y]
```

**Comment by tbaddade** [comment]
> Man hätte also schon damals das JS von jonom mit eigenem Code - im Frontend - aktivieren müssen

Korrekt, die Idee von jonom war m.W. damals die Basis für dieses Addon. Dazu kann @olien aber mehr sagen

**Comment by olien** [comment]
Stimmt. Das war die Basis. Durch die MM Typen wurde das wohl nicht mehr benutzt. 
Da die FP Werte ja aus der DB geholt werden können kann man ja immer noch mit dem JS arbeiten - oder? Ist halt nur nicht mehr mitgeliefert...

**Comment by christophboecker** [comment]
nabend zusammen. Da sich hier nichts mer tut und die Frage geklärt ist schieße ich das Issue.
