### ISSUE TITLE
Optionen verständlicher machen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/focuspoint#59]
Die Bedienung bzw. die Auswahl der Optionen war vorher einfacher und verständlicher.

**Comment by christophboecker** [comment]
Danke für das Feedback. Was konkret meinst Du und was wäre Dein Verbesserungsvorschlag?

**Comment by skerbis** [comment]
Die Select-Optionen waren vorher direkt beschrieben und so verständlicher.  
Koordinate / Ersatzwert: hier wird nicht klar was zu machen ist.
Die Trennung in 2 Eingabefeldern wie in der Vorversion ist einfacher und verständlicher, finde ich. 

Dennoch ein sehr gelungenes Addon. Ich liebe die neue Vorschaufunktion mit Vergrößerung. :-)

**Comment by christophboecker** [comment]
Die zwei Felder der Vorversion bezogen sich ja auf zwei Koordinatensysteme. Jetzt gibt es nur noch eines. Und daran was zu ändern wäre ein sehr tiefer Eingriff ins Addon. Ich schließe dann mal dieses Issue mit ZZTop-Bart
