### ISSUE TITLE
focuspoint_resize erstellt zu kleine Bilder

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/focuspoint#60]
**Effekt Werte**

| Label | Wert |
| --- | --- |
| Basisfeld (med_...) | med_focuspoint |
| Koordinate / Ersatzwert | | 
| Zielgröße: Breite | 2600 | 
| Zielgröße: Höhe | | 
| Modus: | maximum |

**Bild Werte**

| Label | Wert |
| --- | --- |
| Focalpoint des Bildes | 50.0%,95.0% | 
| Breite / Höhe des Bildes | 2600px / 1953px |

**Ausgabe**

Das Bild wird dann mit `2.600px x 212px` ausgegeben. Erwartet hätte ich die Originalgröße des Bildes von ` 2600px x 1953px`

**Comment by christophboecker** [comment]
Kann ich nix zu sagen. Der Effekt focuspoint_resize ist noch im Paket, weil ich ihn nicht Knall auf Fall rauswerfen wollte. Auf alle Anfragen vorher, wer in nutzt, habe ich keine positive Rückmeldung bekommen. Support ist eingestellt (siehe Change-Log etc.) 

Oder geht es um focuspoint_fit?

**Comment by tbaddade** [comment]
Es geht um den Effekt `focuspoint_resize` nicht um den `focuspoint_fit`. Der `focuspoint_resize` Effekt machte genau das was der mitgelieferte `resize`Effekt macht nur unter Berücksichtigung des Focalpointes.

**Comment by christophboecker** [comment]
Sorry, aber dann bin ich raus.

**Comment by olien** [comment]
Den Effekt hat damals Jan gebaut. Bin davon ausgegangen, dass der auch in der neuen Version funktioniert.

**Comment by christophboecker** [comment]
Ich schau mir das Teil noch mal an. Schließlich habe ich es auf die aktuelle Variante umgestellt.

**Comment by tbaddade** [comment]
> Ich schau mir das Teil noch mal an

Danke dir

**Comment by christophboecker** [comment]
Frage an Oliver: was hat Jan genau gebaut damals - den Original-Resize im Media-Manager oder (auch) den Focuspoint-Resize? Nur der letztere liefert die seltsamen Ergebnisse.

**Comment by olien** [comment]
Ich vermute beide. Ganz sicher aber den Focuspoint Effekt.

**Comment by christophboecker** [comment]
Frage an Thomas: setzt du den Effekt Focuspoint-Resize erstmalig ein? 

Die Funktion war schon immer seltsam und die Ergebnisse, die Du nun siehtst und eben nicht Deinen Erwartungen entsprechen (meinen auch nicht, nebenbei angemerkt), sind komplett normal und waren schon immer so. Deshalb hier mal die Gegenüberstellung verschiedener Varianten (gleiche Parameter, unterschiedlicher Fokuspunkt), durchgeführt mit Version 1.4.2, also der alten Version!

Das Quellbild ist im Querformat, die Zielbild-Parameter sind:
* Breite 1000
* Höhe variabel (keine Vorgabe)
* Modus "maximum".

Zuerst die Fokuspunkte von links nach rechts gesetzt, also links außen, Mitte, rechts außen:
 <img width="971" alt="grafik" src="https://user-images.githubusercontent.com/10065904/46162245-f618e400-c287-11e8-8ce8-92a40c2acb62.png">

Und nun von oben nach unten:
<img width="959" alt="grafik" src="https://user-images.githubusercontent.com/10065904/46163206-c91a0080-c28a-11e8-88b2-bfbef5409f25.png">

Da ich den Code für FP2 nur minimal angpaßt habe (betreffend Abruf der FP-Koordinaten), errechnet die aktuelle Version genauso unerwartete Ergebnisse wie die alte.

**Comment by christophboecker** [comment]
@dergel Ping!

**Comment by tbaddade** [comment]
> setzt du den Effekt Focuspoint-Resize erstmalig ein?

nein aber recht selten. Aufgefallen ist es mir auch nur, da bereits ein Bild, welches ich für Testzwecke verwendet hatte, einen Focalpoint von 50/90 hatte. Mal sehen was Jan dazu meint.

**Comment by dergel** [comment]
ich werde gerade nicht dazu kommen und bis erstmal eine Woche im Urlaub..

**Comment by christophboecker** [comment]
Hallo Kollegen, kann ich das Issue schließen?

**Comment by tbaddade** [comment]
> kann ich das Issue schließen?

Wenn der Fehler bereits in der 1.4er Version enthalten ist, ist es m.E. auch weiterhin ein Fehler in der neuen Version auch wenn beide Versionen das gleiche Ergebnis liefert.

**Comment by christophboecker** [comment]
Das ist kein Fehler. Das ist "Works as designed". :-)

**Comment by christophboecker** [comment]
Hi Jan. Machst Du da noch mal was? Ansonsten schließe ich das Issue. Danke

**Comment by marcohanke** [comment]
Ich hab' hier gerade genau das gleiche "Problem", aber wenn Focuspoint-Resize sowieso deprecated ist eigentlich hinfällig. @tbaddade was spricht an der Stelle Focuspoint Fit mit 0% ?

**Comment by christophboecker** [comment]
OK, Jan macht auch nix, dann schließe ich das jetzt.
