### ISSUE TITLE
Codebeispiele verständlicher machen

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/focuspoint#65]
Yes, das Addon sieht im Backend schon super aus und ist schön zu bedienen. Danke!

Auch die Doku sieht toll aus. Als Modul-Entwickler ist mir leider noch nicht ganz klar, was ich tun muss, um meine Bilder mit Fokus zu bekommen. Ich vermute, dass die Codepassage

```
$fpMedia = focuspoint_media::get( $filename );

if ( $fpMedia )
{
    list( $fx,$fy ) = fpMedia->getFocus( 'med_focuspoint_face', [50,60], true );

    ....

}
```

die Nutzung im Modulcode beschreibt, aber so ganz klar ist mir das nicht. Prima wäre, wenn es eine Sektion für eine Beispiel-Modulausgabe gäbe. Dann wird die Verwendung etwas klarer, denke ich.

**Comment by christophboecker** [comment]
Das Code-Beispiel kommt an zwei Stellen im Abschnitt "Für Entwickler" vor, wenn ich nicht irre. Einmal im Kapitel  "Klasse focuspoint_media" und einmal im Kapitel "Eigene Fokuspunkt-Effekte entwickeln". Im ersten Fall geht es um die Funktionsweise der Klasse focuspoint_media als Alternative für rex_media - halt mit Zusatzfunktion um den Foscuspunkt abzurufen. Die andere Varante ist ein Rohling für einen eigenen Media-Manager-Effekt mit Focuspunkt-Bezug. Ansonsten: Bilder sollten immer über den Media-Manager erzeugt werden. Das ist also keine Modulfrage, sondern nur wie der Bilder-Link im <img>-Tag aussieht.  

Der obige Code ist für Modulentwickler nur dann relevant, wenn sie die Bilder eben nicht über den Media-Manager erzeugen, sondern irgendwas Eigenes machen wollen und dafür den Focuspinkt benötigen. Was auch immer das wäre. Der Abruf würde auch mit einem rex_mdia-Objekt funktionieren (getValue('med_focuspoint')), aber mit der Klasse sind auch schon die Fallbacks berücksichtigt und es kommt immer ein valider Wert.

Ich nehm den Hinweis aber mal auf, dass die Empfehlung zur Ausgabe etwas prominenter platziert wird als als letzter Absatz in der "Übersicht": _Bilder werden z.B. über Effekte im Media-Manager Fokuspunkt-bezogen erzeugt._ und baue das das im nächsten Release ein.

**Comment by cukabeka** [comment]
Cool, danke für die Erklärung. 

Ich weiß zugegeben allerdings gerade immer noch nicht, was ich tun muss, um das Addon zu nutzen? 

Muss ich also mein Modul umschreiben und focuspoint_media statt rex_media nutzen? Fände da einfach ein vorher-nachher Beispiel hilfreich.

**Comment by christophboecker** [comment]
statt `<img src="media/filename.jpg">` nimmst Du `<img src="index.php?rex_media_type=meinmediamanagertype&rex_media_file=filename.jpg">`. Und im Media-Manager legst Du einen Media-Type "meinmediamanagertype" an und der bekommt den Effekt "focuspoint_fit" zugewiesen.  Ist aber kein FP-Thema, sondern ein MM-Thema.

**Comment by tbaddade** [comment]
Hast du yrewrite im Einsatz, kannst du auch `src="/images/meinmediamanagertype/filename.jpg"` notieren.

**Comment by christophboecker** [comment]
Ich denke mal, das hat sich erledigt.
