### ISSUE TITLE
MediaType "focuspoint_media_detail" vorm löschen schützen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/focuspoint#69]
Beim absetzen des Query's den Status auf `1` setzen.

**Comment by christophboecker** [comment]
Könnst Du das bitte etwas genauer beschreiben. Danke!

**Comment by tbaddade** [comment]
Beim absetzen des Query, wo du den MediaType in die DB speicherst, den Value für das Feld `status` auf `1` setzen. In der Liste wird dann der Löschenlink mit Systemplugin ersetzt

**Comment by christophboecker** [comment]
Jaaaah, das ist mir bekannt. Ich hab damals ganz bewußt nicht die Möglichkeit genutzt, den Status auf 1 zu setzen, denn ... Focuspoint ist kein System-Addon. Wäre natütlich schicker weil einfacher. Wie war es denn seinerzeit gedacht? Sollte das Flag nur für Core-Medientypen gelten oder generell frei verfügbar sein auch für Addon-interne Medientyen?

**Comment by tbaddade** [comment]
> Sollte das Flag nur für Core-Medientypen gelten oder generell frei verfügbar sein auch für Addon-interne Medientyen?

Ich sehe den Status für alle AddOns an. Das AddOn benötigt diesen Typen mit seinen Effekten und sollte durch andere m.E. nicht gelöscht werden.

**Comment by christophboecker** [comment]
Das wäre nicht mehr hinreichend eindeutig. Wenn ein Mediatyp als "System Mediatyp" geflagged ist, würde ich ihn ohne zu zögern in einem Addon benutzen. Er wurde mit dem Core+ ausgeliefert. Bei Medientypen, die mit einem Addon kommen, würde nicht mehr auffallen, dass sie mit einem AddOn kamen und nicht mit dem Core. Da hat man schnell bei einem selbst geschriebenen (FOR-)Addon übersehen, die nötigen Requirements in der package.yml zu definieren. (Abgesehen davon:ein ganzes Addon-Installieren nur für den MediaTyp? Overkill!).

Was sagt denn das Orakel @gharlan? MediaManager-Typen in Addons als "System Mediatyp" kennzeichnen um Löschschutz zu erreichen oder ist das Flag nur für MediaManager-Typen des Core+ gedacht?

**Comment by christophboecker** [comment]
Aber ich gebe Dir recht: ein AddOn müsste irgendwie verhindern können, dass Mediatypen gelöscht werden. Und eigentlich dachte ich, dass ich das auch dringehabt hätte in Focuspoint - war wohl Wunsch. 

Und es gibt noch ein Problem: wenn der Mediatyp (oder auch ein Effekt oder ein Meta-Datentyp), der von einem AddOn zugeliefert wird, außerhalb des Addon genutzt wird, gibt es sowieso eklige Rückbezüge. 

Beispiel: Addon bringt einen Effekt mit, der wird in einem Mediatyp außerhalb des Addons benutzt (von Hand angelegt). Hier gibt es keinen Löschschutz über definierte Abhängigkeiten. Deinstalliert man das Addon, geht der Media-Manager auf die Bretter, sobald man die Effekte des Typs bearbeiten will oder ein Bild des Typs anlagen will. Evtl reicht schon Deaktivieren.

**Comment by christophboecker** [comment]
Querprüfungen, Änderungs- und Löschsperren eingebaut mit V2.1 #70
