### ISSUE TITLE
Versionsangaben konfus

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/focuspoint#77]
Ein Update von Version 2.1.0 auf Version 2.1.1 zieht ein Update des Core auf 5.8 nach.
Verwirrt ich bin ;)

**Comment by christophboecker** [comment]
Mit Version Redaxo 5.8.0 hat sich die Art und Weise, geändert, wie der FP-Code in die Sidebar des Media-Managers gehängt wird. Die neue Version von FP ist Folge, nicht Ursache.
