### ISSUE TITLE
effect klasse noch anpassen

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/focuspoint#8]
sobald mal einen focuspoint gesetzt hat - und dieser im image_manager mit der focuspoint klasse verwendet wird - ändert sich das bildformat, weil, abhaengig vom focuspoint, das größtmögliche format genommen wird.

das könnte man noch optional einsetzen. Bildformat beibehalten als checkbox wäre gut.

Eventuell könnte man auch einen Zoom noch mit einplanen.. Sowas wie .. Bildzoom zum focuspoint - in Prozent .. 25/50/75% reinzoomen.

---

Ursprünglich geschrieben von @dergel
Könnte auch hier noch berücksichtigt werden!

**Comment by christophboecker** [comment]
Hi Oliver,
ich bin mir nicht sicher, ob ich Deine Idee mit dem Zoom richtig verstande habe. Aber hiermal mein Ansatz, den ich grade realisiere:

Ausgangspunkt: der Resize-Effekt (auch der in focuspoint) macht halt nicht was ich gerne hätte. Wenn ich z.B. ein 1200x800-Bild nach 400x200 verkleinern will, ist je nach Parameter das Ergebnis größer, mit schwarzen Rändern oder gestaucht. Meine Ziel ist, das Bild bestmöglich einzupassen und den Rest abzuschneiden. Im Beispiel würde also über die Breite eingepasst und der Überstand in der Höhe oben und unten je 100 gekappt. Focuspoint ermöglich natürlich, den Kappbereich intelligent zu wählen.

Und natürlich: wenn der Zielbereich deutlich kleiner ist als das Original, geht womöglich zu viel verloren. Zoom? Zoom!

Mein Effekt focuspoint_fit arbeitet so:

Parameter
* **Zielbild-Größe:** Höhe und/oder Breite. Falls eine Angabe fehlt, wird sie über die AspectRatio des Originalbildes ermittelt.   
* **Default für den Fokus:** Falls das Bild keinen Fokuspunkt (med_focuspoint_css) hat, werden die Default-Werte genommen. Angabe als %-Wert. Default ist 50/50 = Mitte
* **Zoom-Faktor:** Im ersten Wurf mal ein Select mit 0/25/50/75/100.

Vorgehen 

* **Zoom:** Wenn wie im obigen Beispiel aufgrund der Seitenverhältnisse über die Breite angeglichen wird, würde über die Breite der Restplatz ermittelt. Beispiel: 800 px als Delta von 1200 (Bild) und 400 (Ziel). Dieses Delta wird mit dem Zoom-Faktor multipliziert. 25% Zoom = 200px. Um diesen Betrag wird der Auschnitt in der Breite des Ausschnitts auf 600px vergrößert. Unter Beibehaltung des AspectRatio des Zielbildes erhöht sich die Ausschnittshöhe auf 300.
* **Auschnitt platzieren:** Der Auschnitt wird erst mal mittig um den Focuspoint ausgerichtet. Falls der Auschnitt übersteht, wird er so verschoben, dass er wieder innerhalb des Bildes liegt. Der FP ist dann natürlich nicht mehr mittig im Ausschnitt. Aber dass lässt sich halt schlecht verhindern - speziell wenn der FP eh im Randbereich liegt.Sonst müsste der Auschnitt verkleinert werden, was die Qualität verschlechtert.
* **Sonderfall "Bild kleiner als Auschnitt":** Dann wird der Zoom-Faktor ignoriert und der Ausschnitt proportional so verkleinert, dass er in das Bild passt. Bedeutet letztlich, dass das Bild vegrößert wird. Da die AspectRatio des Zielbereichs maßgeblich ist, würe evtl. auch noch etwas gekappt werden.

Mit diesen Daten reicht dann ein einziges imagecopyresampled, um das Zielbild zu erstellen. 

Die Frage "enlarge or no_enlarge" stelle ich nicht :-). Für knapp zu kleine Bilder ist es wurscht und für stark zu kleine Bilder sollte man besser mal darüber nachdenken, andere Bilder zu nehmen. Imho.

Die Sache mit minimized/maximized schenke ich mir auch komplett. Halte ich für überflüssig wenn eh ein Auschnitt genommen wird. Gestaucht wird auch nix.

Der Effekt funktioniert übrigens auch unabhängig von focuspoint :-) wegen der Default-Werte 

Wäre das die Sache, die Dir vorschwebt? Dann würde ich es etwas runder machen und als Pull einstellen. Oder einfacher: ich schicke Dir die Datei mit dem Effekt per Mail. Mein Vorschlag wäre dann, den Effekt zusätzlich entweder in den Medien-Manager zu übernehmen oder nach focuspoint. Also nicht als Ersatz für resize :-)

Grüße
Chris

(mal sehen wie viele Schreibfehler ich wieder erst nach dem Absenden finde )

**Comment by olien** [comment]
Hallo Chris,

so viele Gedanken habe ich dazu noch gar nicht gemacht (war ja die Idee von @dergel :-)),

Was Du schreibst hört sich gut an. Vielleicht ist der PR besser hier https://github.com/redaxo/redaxo aufgehoben wenn der Effekt nicht vom Focuspoint abhängig ist. Wenn nicht. Dann sehr gerne hier!

LG
Oliver

**Comment by olien** [comment]
Ist erledigt. DANKE!
