### ISSUE TITLE
Ausgabe der Effekt-Beschreibung

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/focuspoint#81]
Es wäre schön, wenn im Bereich Medien bearbeiten bei Fokuspunkt-Auswahl außer den Namen der Fokuspunkte auch die Beschreibung ausgegeben werden würde. 
Ich nutze sie, um die recht technischen Namen der Fukuspunkte etwas sprechender für die Radaktion zu machen.
Also etwa in der Art "Beschreibung [Name]" z.B. "Quadratischer Ausschnitt 200x200px [quadratischer_ausschnitt_200x200]"

**Comment by christophboecker** [comment]
Wovon sprichst Du jetzt konkret? ich kann Dir grade nicht folgen. Der Fokuspunkt hat erstmal nix zu tun mit "Quadratischer Ausschnitt 200x200px " oder anderen Texten, denn das ist ja die Beschreibung eines Media-Manager-Effektes.

**Comment by DanielWeitenauer** [comment]
Ich meine diese Liste:

![image](https://user-images.githubusercontent.com/3332367/68070686-a998b580-fd71-11e9-8c66-17e0bde5b7fa.png)

Da dort die Namen ausgegeben werden, die ja auch für die URL benutzt werden müssen, ist die Liste recht schlecht zu lesen. Die Beschreibung bietet etwas mehr Formatierungsmöglichkeiten.

**Comment by christophboecker** [comment]
Jetzt hab ich´s verstanden. Es hatte einen (vermeintlich) guten Grund, warum das so ist wie es ist. Nur fällt er mir nicht mehr ein. Ich nehm die Sache auf die Liste für das nächste Release. Danke.

**Comment by DanielWeitenauer** [comment]
Super, danke!

**Comment by christophboecker** [comment]
Hi Daniel,

das ist eine zweischneidige Angelegenheit. DU macht es diszipliniert (prägnante Medien-Typ-Beschreibung, nicht zu lang), aber andere? nix oder episch lang Platz/Layout sprengend oder mit anderer inhaltlichen Intention? Was dem einen hilft ist bein anderen eine böse Falle. Ich würde von daher ungerne die Detailbeschreibung bevorzugt ausgeben (wie in einem Beispiel).

Ich denke eher an einen Extension-Point. Der bekommt die Liste der ermittelten Medientypen und dann kann man ja umbauen wenn gewünscht.

**Comment by DanielWeitenauer** [comment]
Dass es Probleme geben könnte hatte ich auch schon überlegt. hätte mir auch was zurechtgefummelt, hab aber die passenden Stellen im Code nicht finden können. 
Mit der Möglichkeit es selbst anzupassen gäbe es sogar noch mehr Variationsmöglichkeiten: gruppieren, filtern, umsortieren...

**Comment by christophboecker** [comment]
Die fragliche Stelle ist in lib/focuspoint.php in der Methode show_sidebar:
https://github.com/FriendsOfREDAXO/focuspoint/blob/6f0dce9e9c72f1e97fa22510c3f787588429ff10/lib/focuspoint.php#L94-L100
Der Array-Key ist der MM-Typ-Name, der Array-Value die Liste FP-Felder im Effekt. (Wobei das Stand heute nur eines sein sollte, denn zwei FP-Fit hintereinander in einem MM-Type ist meist Blödsinn, aber nicht unbedingt immer.

**Comment by christophboecker** [comment]
Siehe PR #85
