### ISSUE TITLE
Min-php version in package.yml notieren

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/focuspoint#83]

**Comment by christophboecker** [comment]
Bist Du auf was gestoßen, das mit PHP 7.1.3 noch nicht funktioniert? 
Benötigt Focuspoint eine höhere PHP-Version?
 
﻿

**Comment by staabm** [comment]
Nein, mir ist nur aufgefallen dass keine mindestversion definiert ist

Auf die mindestversion des cores würde ich mich nicht verlassen

**Comment by christophboecker** [comment]
Du erschütterst grade mein Vertrauen in den Core.
﻿

**Comment by staabm** [comment]
jedes paket sollte seine eigenen mindest defintionen haben.
auf externe und/oder transitive abhängigkeiten die sich ausserhalb deines einflusses ständig ändern, solltest du nicht bauen. ist bad practice.

fiktiv: wenn wir morgen redaxo 5.10 releasen mit php8 unterstützung fliegt jedem dein addon um die ohren, falls es probleme mit php8 hat. du bringst dich damit selbst in zugzwang.

**Comment by christophboecker** [comment]
erledigt mit PR #82
