### ISSUE TITLE
Class 'Parsedown' not found

### ISSUE THREAD

**Issue by georgkaser** [FriendsOfREDAXO/focuspoint#9]
"ErrorException" thrown in ..../redaxo/src/addons/focuspoint/pages/info.php on line 4
Fatal error: Class 'Parsedown' not found

Anmerkung: Mit installiertem epiceditor funktionierts. Sollte vielleicht drauf hingewiesen werden - nicht jeder hat epiceditor installiert.

**Comment by olien** [comment]
Der epiceditor wir die Parsedown Class liefern. ich korrigiere das ... danke für den Hinweis

**Comment by phoebusryan** [comment]
Das hat sich wohl erübrigt, da Redaxo mittlerweile Parsedown mitliefert.

**Comment by olien** [comment]
jo
