### ISSUE TITLE
Darstellung Medientyp focuspoint_media_detail 

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/focuspoint#92]
Für den Medientyp focuspoint_media_detail sind die Links bearbeiten, Effekte bearbeiten und löschen unklickbar. Ich musste den Medientyp gerade anpassen und sowas ist schlicht überflüssig.

**Comment by christophboecker** [comment]
Hi Ingo, das ist nun mal ein systeminterner Typ und der soll nicht geändert oder gelöscht werden. Was passt denn daran nicht?

**Comment by IngoWinter** [comment]
Ich brauchte einen zusätzlichen Effekt. Ich denke bei den Redaxo System Medientypen ist es besser gelöst. Die kann man nicht aus Versehen löschen, aber bei Bedarf anpassen.

**Comment by christophboecker** [comment]
Ich hab Deinen Punkt aufgenommen; der PR ist eingestellt und kommt in Kürze mit V3 in die freie Wildbahn. Das Issue schließe ich. Danke für die Anregung.
